
export const provincias = [
  { provinciaId: 1,  provinciaNombre: "Buenos Aires" },
  { provinciaId: 2,  provinciaNombre: "Catamarca" },
  { provinciaId: 3,  provinciaNombre: "Chaco" },
  { provinciaId: 4,  provinciaNombre: "Chubut" },
  { provinciaId: 5,  provinciaNombre: "Córdoba" },
  { provinciaId: 6,  provinciaNombre: "Corrientes" },
  { provinciaId: 7,  provinciaNombre: "Entre Ríos" },
  { provinciaId: 8,  provinciaNombre: "Formosa" },
  { provinciaId: 9,  provinciaNombre: "Jujuy" },
  { provinciaId: 10, provinciaNombre: "La Pampa" },
  { provinciaId: 11, provinciaNombre: "La Rioja" },
  { provinciaId: 12, provinciaNombre: "Mendoza" },
  { provinciaId: 13, provinciaNombre: "Misiones" },
  { provinciaId: 14, provinciaNombre: "Neuquén" },
  { provinciaId: 15, provinciaNombre: "Río Negro" },
  { provinciaId: 16, provinciaNombre: "Salta" },
  { provinciaId: 17, provinciaNombre: "San Juan" },
  { provinciaId: 18, provinciaNombre: "San Luis" },
  { provinciaId: 19, provinciaNombre: "Santa Cruz" },
  { provinciaId: 20, provinciaNombre: "Santa Fe" },
  { provinciaId: 21, provinciaNombre: "Santiago del Estero" },
  { provinciaId: 22, provinciaNombre: "Tierra del Fuego" },
  { provinciaId: 23, provinciaNombre: "Tucumán" },
];