
const paisesAmerica = [
  // ===== AMÉRICA DEL NORTE =====
  {
    id: "CAN",
    nombre: "Canadá",
    capital: "Ottawa",
    region: "América del Norte",
    bandera: "https://flagcdn.com/w320/ca.png",
    poblacion: 38000000,
    superficie: 9984670,
    idioma: "Inglés y Francés",
    moneda: "Dólar canadiense",
    añoIndependencia: 1867
  },
  {
    id: "USA",
    nombre: "Estados Unidos",
    capital: "Washington D. C.",
    region: "América del Norte",
    bandera: "https://flagcdn.com/w320/us.png",
    poblacion: 333000000,
    superficie: 9833517,
    idioma: "Inglés",
    moneda: "Dólar estadounidense",
    añoIndependencia: 1776
  },
  {
    id: "MEX",
    nombre: "México",
    capital: "Ciudad de México",
    region: "América del Norte",
    bandera: "https://flagcdn.com/w320/mx.png",
    poblacion: 128000000,
    superficie: 1964375,
    idioma: "Español",
    moneda: "Peso mexicano",
    añoIndependencia: 1810
  },

  // ===== AMÉRICA CENTRAL =====
  {
    id: "BLZ",
    nombre: "Belice",
    capital: "Belmopán",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/bz.png",
    poblacion: 420000,
    superficie: 22966,
    idioma: "Inglés",
    moneda: "Dólar beliceño",
    añoIndependencia: 1981
  },
  {
    id: "CRI",
    nombre: "Costa Rica",
    capital: "San José",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/cr.png",
    poblacion: 5100000,
    superficie: 51100,
    idioma: "Español",
    moneda: "Colón costarricense",
    añoIndependencia: 1821
  },
  {
    id: "SLV",
    nombre: "El Salvador",
    capital: "San Salvador",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/sv.png",
    poblacion: 6500000,
    superficie: 21041,
    idioma: "Español",
    moneda: "Dólar estadounidense",
    añoIndependencia: 1821
  },
  {
    id: "GTM",
    nombre: "Guatemala",
    capital: "Ciudad de Guatemala",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/gt.png",
    poblacion: 18000000,
    superficie: 108889,
    idioma: "Español",
    moneda: "Quetzal guatemalteco",
    añoIndependencia: 1821
  },
  {
    id: "HND",
    nombre: "Honduras",
    capital: "Tegucigalpa",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/hn.png",
    poblacion: 10000000,
    superficie: 112492,
    idioma: "Español",
    moneda: "Lempira hondureña",
    añoIndependencia: 1821
  },
  {
    id: "NIC",
    nombre: "Nicaragua",
    capital: "Managua",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/ni.png",
    poblacion: 7000000,
    superficie: 130373,
    idioma: "Español",
    moneda: "Córdoba nicaragüense",
    añoIndependencia: 1821
  },
  {
    id: "PAN",
    nombre: "Panamá",
    capital: "Ciudad de Panamá",
    region: "América Central",
    bandera: "https://flagcdn.com/w320/pa.png",
    poblacion: 4400000,
    superficie: 75417,
    idioma: "Español",
    moneda: "Balboa panameño y Dólar estadounidense",
    añoIndependencia: 1903
  },

  // ===== CARIBE =====
  {
    id: "ATG",
    nombre: "Antigua y Barbuda",
    capital: "Saint John's",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/ag.png",
    poblacion: 93000,
    superficie: 442,
    idioma: "Inglés",
    moneda: "Dólar del Caribe Oriental",
    añoIndependencia: 1981
  },
  {
    id: "BHS",
    nombre: "Bahamas",
    capital: "Nasáu",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/bs.png",
    poblacion: 400000,
    superficie: 13943,
    idioma: "Inglés",
    moneda: "Dólar bahameño",
    añoIndependencia: 1973
  },
  {
    id: "BRB",
    nombre: "Barbados",
    capital: "Bridgetown",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/bb.png",
    poblacion: 280000,
    superficie: 430,
    idioma: "Inglés",
    moneda: "Dólar barbadense",
    añoIndependencia: 1966
  },
  {
    id: "CUB",
    nombre: "Cuba",
    capital: "La Habana",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/cu.png",
    poblacion: 11200000,
    superficie: 109884,
    idioma: "Español",
    moneda: "Peso cubano",
    añoIndependencia: 1902
  },
  {
    id: "DMA",
    nombre: "Dominica",
    capital: "Roseau",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/dm.png",
    poblacion: 72000,
    superficie: 751,
    idioma: "Inglés",
    moneda: "Dólar del Caribe Oriental",
    añoIndependencia: 1978
  },
  {
    id: "GRD",
    nombre: "Granada",
    capital: "Saint George's",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/gd.png",
    poblacion: 113000,
    superficie: 344,
    idioma: "Inglés",
    moneda: "Dólar del Caribe Oriental",
    añoIndependencia: 1974
  },
  {
    id: "HTI",
    nombre: "Haití",
    capital: "Puerto Príncipe",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/ht.png",
    poblacion: 11500000,
    superficie: 27750,
    idioma: "Francés y Criollo haitiano",
    moneda: "Gourde haitiano",
    añoIndependencia: 1804
  },
  {
    id: "JAM",
    nombre: "Jamaica",
    capital: "Kingston",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/jm.png",
    poblacion: 3000000,
    superficie: 10991,
    idioma: "Inglés",
    moneda: "Dólar jamaicano",
    añoIndependencia: 1962
  },
  {
    id: "DOM",
    nombre: "República Dominicana",
    capital: "Santo Domingo",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/do.png",
    poblacion: 11000000,
    superficie: 48671,
    idioma: "Español",
    moneda: "Peso dominicano",
    añoIndependencia: 1844
  },
  {
    id: "KNA",
    nombre: "San Cristóbal y Nieves",
    capital: "Basseterre",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/kn.png",
    poblacion: 55000,
    superficie: 261,
    idioma: "Inglés",
    moneda: "Dólar del Caribe Oriental",
    añoIndependencia: 1983
  },
  {
    id: "VCT",
    nombre: "San Vicente y las Granadinas",
    capital: "Kingstown",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/vc.png",
    poblacion: 110000,
    superficie: 389,
    idioma: "Inglés",
    moneda: "Dólar del Caribe Oriental",
    añoIndependencia: 1979
  },
  {
    id: "LCA",
    nombre: "Santa Lucía",
    capital: "Castries",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/lc.png",
    poblacion: 185000,
    superficie: 617,
    idioma: "Inglés",
    moneda: "Dólar del Caribe Oriental",
    añoIndependencia: 1979
  },
  {
    id: "TTO",
    nombre: "Trinidad y Tobago",
    capital: "Puerto España",
    region: "Caribe",
    bandera: "https://flagcdn.com/w320/tt.png",
    poblacion: 1400000,
    superficie: 5131,
    idioma: "Inglés",
    moneda: "Dólar de Trinidad y Tobago",
    añoIndependencia: 1962
  },

  // ===== AMÉRICA DEL SUR =====
  {
    id: "ARG",
    nombre: "Argentina",
    capital: "Buenos Aires",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/ar.png",
    poblacion: 46000000,
    superficie: 2780400,
    idioma: "Español",
    moneda: "Peso argentino",
    añoIndependencia: 1816
  },
  {
    id: "BOL",
    nombre: "Bolivia",
    capital: "Sucre",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/bo.png",
    poblacion: 12000000,
    superficie: 1098581,
    idioma: "Español, Quechua, Aymara",
    moneda: "Boliviano",
    añoIndependencia: 1825
  },
  {
    id: "BRA",
    nombre: "Brasil",
    capital: "Brasilia",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/br.png",
    poblacion: 214000000,
    superficie: 8515767,
    idioma: "Portugués",
    moneda: "Real brasileño",
    añoIndependencia: 1822
  },
  {
    id: "CHL",
    nombre: "Chile",
    capital: "Santiago",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/cl.png",
    poblacion: 19000000,
    superficie: 756102,
    idioma: "Español",
    moneda: "Peso chileno",
    añoIndependencia: 1818
  },
  {
    id: "COL",
    nombre: "Colombia",
    capital: "Bogotá",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/co.png",
    poblacion: 52000000,
    superficie: 1141748,
    idioma: "Español",
    moneda: "Peso colombiano",
    añoIndependencia: 1810
  },
  {
    id: "ECU",
    nombre: "Ecuador",
    capital: "Quito",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/ec.png",
    poblacion: 18000000,
    superficie: 276841,
    idioma: "Español",
    moneda: "Dólar estadounidense",
    añoIndependencia: 1822
  },
  {
    id: "GUY",
    nombre: "Guyana",
    capital: "Georgetown",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/gy.png",
    poblacion: 800000,
    superficie: 214969,
    idioma: "Inglés",
    moneda: "Dólar guyanés",
    añoIndependencia: 1966
  },
  {
    id: "PRY",
    nombre: "Paraguay",
    capital: "Asunción",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/py.png",
    poblacion: 7000000,
    superficie: 406752,
    idioma: "Español y Guaraní",
    moneda: "Guaraní paraguayo",
    añoIndependencia: 1811
  },
  {
    id: "PER",
    nombre: "Perú",
    capital: "Lima",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/pe.png",
    poblacion: 34000000,
    superficie: 1285216,
    idioma: "Español, Quechua, Aymara",
    moneda: "Sol peruano",
    añoIndependencia: 1821
  },
  {
    id: "SUR",
    nombre: "Surinam",
    capital: "Paramaribo",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/sr.png",
    poblacion: 600000,
    superficie: 163821,
    idioma: "Neerlandés",
    moneda: "Dólar surinamés",
    añoIndependencia: 1975
  },
  {
    id: "URY",
    nombre: "Uruguay",
    capital: "Montevideo",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/uy.png",
    poblacion: 3500000,
    superficie: 176215,
    idioma: "Español",
    moneda: "Peso uruguayo",
    añoIndependencia: 1828
  },
  {
    id: "VEN",
    nombre: "Venezuela",
    capital: "Caracas",
    region: "América del Sur",
    bandera: "https://flagcdn.com/w320/ve.png",
    poblacion: 28000000,
    superficie: 916445,
    idioma: "Español",
    moneda: "Bolívar",
    añoIndependencia: 1811
  }
];

export default paisesAmerica;
