export const paises = [
    { id: 32, nombrePais: "ARGENTINA", continentePais: "AMERICA DEL SUR", poblacionPais: 47000000, capital: "BUENOS AIRES", bandera: "https://flagcdn.com/w320/ar.png", codigoAlpha2: "AR", codigoAlpha3: "ARG" },
    { id: 76, nombrePais: "BRASIL", continentePais: "AMERICA DEL SUR", poblacionPais: 213000000, capital: "BRASILIA", bandera: "https://flagcdn.com/w320/br.png", codigoAlpha2: "BR", codigoAlpha3: "BRA" },
    { id: 152, nombrePais: "CHILE", continentePais: "AMERICA DEL SUR", poblacionPais: 19000000, capital: "SANTIAGO", bandera: "https://flagcdn.com/w320/cl.png", codigoAlpha2: "CL", codigoAlpha3: "CHL" },
    { id: 858, nombrePais: "URUGUAY", continentePais: "AMERICA DEL SUR", poblacionPais: 3500000, capital: "MONTEVIDEO", bandera: "https://flagcdn.com/w320/uy.png", codigoAlpha2: "UY", codigoAlpha3: "URY" },
    { id: 600, nombrePais: "PARAGUAY", continentePais: "AMERICA DEL SUR", poblacionPais: 7100000, capital: "ASUNCION", bandera: "https://flagcdn.com/w320/py.png", codigoAlpha2: "PY", codigoAlpha3: "PRY" },
    { id: 68, nombrePais: "BOLIVIA", continentePais: "AMERICA DEL SUR", poblacionPais: 11600000, capital: "LA PAZ", bandera: "https://flagcdn.com/w320/bo.png", codigoAlpha2: "BO", codigoAlpha3: "BOL" },
    { id: 604, nombrePais: "PERU", continentePais: "AMERICA DEL SUR", poblacionPais: 33000000, capital: "LIMA", bandera: "https://flagcdn.com/w320/pe.png", codigoAlpha2: "PE", codigoAlpha3: "PER" },
    { id: 218, nombrePais: "ECUADOR", continentePais: "AMERICA DEL SUR", poblacionPais: 17600000, capital: "QUITO", bandera: "https://flagcdn.com/w320/ec.png", codigoAlpha2: "EC", codigoAlpha3: "ECU" },
    { id: 170, nombrePais: "COLOMBIA", continentePais: "AMERICA DEL SUR", poblacionPais: 51000000, capital: "BOGOTA", bandera: "https://flagcdn.com/w320/co.png", codigoAlpha2: "CO", codigoAlpha3: "COL" },
    { id: 862, nombrePais: "VENEZUELA", continentePais: "AMERICA DEL SUR", poblacionPais: 28000000, capital: "CARACAS", bandera: "https://flagcdn.com/w320/ve.png", codigoAlpha2: "VE", codigoAlpha3: "VEN" },
  
    { id: 250, nombrePais: "FRANCIA", continentePais: "EUROPA", poblacionPais: 67000000, capital: "PARIS", bandera: "https://flagcdn.com/w320/fr.png", codigoAlpha2: "FR", codigoAlpha3: "FRA" },
    { id: 276, nombrePais: "ALEMANIA", continentePais: "EUROPA", poblacionPais: 83000000, capital: "BERLIN", bandera: "https://flagcdn.com/w320/de.png", codigoAlpha2: "DE", codigoAlpha3: "DEU" },
    { id: 724, nombrePais: "ESPANA", continentePais: "EUROPA", poblacionPais: 47000000, capital: "MADRID", bandera: "https://flagcdn.com/w320/es.png", codigoAlpha2: "ES", codigoAlpha3: "ESP" },
    { id: 380, nombrePais: "ITALIA", continentePais: "EUROPA", poblacionPais: 60000000, capital: "ROMA", bandera: "https://flagcdn.com/w320/it.png", codigoAlpha2: "IT", codigoAlpha3: "ITA" },
    { id: 826, nombrePais: "REINO UNIDO", continentePais: "EUROPA", poblacionPais: 67000000, capital: "LONDRES", bandera: "https://flagcdn.com/w320/gb.png", codigoAlpha2: "GB", codigoAlpha3: "GBR" },
    { id: 752, nombrePais: "SUECIA", continentePais: "EUROPA", poblacionPais: 10000000, capital: "ESTOCOLMO", bandera: "https://flagcdn.com/w320/se.png", codigoAlpha2: "SE", codigoAlpha3: "SWE" },
    { id: 528, nombrePais: "PAISES BAJOS", continentePais: "EUROPA", poblacionPais: 17000000, capital: "AMSTERDAM", bandera: "https://flagcdn.com/w320/nl.png", codigoAlpha2: "NL", codigoAlpha3: "NLD" },
    { id: 756, nombrePais: "SUIZA", continentePais: "EUROPA", poblacionPais: 8600000, capital: "BERNA", bandera: "https://flagcdn.com/w320/ch.png", codigoAlpha2: "CH", codigoAlpha3: "CHE" },
    { id: 40, nombrePais: "AUSTRIA", continentePais: "EUROPA", poblacionPais: 9000000, capital: "VIENA", bandera: "https://flagcdn.com/w320/at.png", codigoAlpha2: "AT", codigoAlpha3: "AUT" },
    { id: 56, nombrePais: "BELGICA", continentePais: "EUROPA", poblacionPais: 11500000, capital: "BRUSELAS", bandera: "https://flagcdn.com/w320/be.png", codigoAlpha2: "BE", codigoAlpha3: "BEL" },
  
    { id: 156, nombrePais: "CHINA", continentePais: "ASIA", poblacionPais: 1412000000, capital: "PEKIN", bandera: "https://flagcdn.com/w320/cn.png", codigoAlpha2: "CN", codigoAlpha3: "CHN" },
    { id: 356, nombrePais: "INDIA", continentePais: "ASIA", poblacionPais: 1393000000, capital: "NUEVA DELHI", bandera: "https://flagcdn.com/w320/in.png", codigoAlpha2: "IN", codigoAlpha3: "IND" },
    { id: 392, nombrePais: "JAPON", continentePais: "ASIA", poblacionPais: 125800000, capital: "TOKIO", bandera: "https://flagcdn.com/w320/jp.png", codigoAlpha2: "JP", codigoAlpha3: "JPN" },
    { id: 410, nombrePais: "COREA DEL SUR", continentePais: "ASIA", poblacionPais: 52000000, capital: "SEUL", bandera: "https://flagcdn.com/w320/kr.png", codigoAlpha2: "KR", codigoAlpha3: "KOR" },
    { id: 704, nombrePais: "VIETNAM", continentePais: "ASIA", poblacionPais: 97000000, capital: "HANOI", bandera: "https://flagcdn.com/w320/vn.png", codigoAlpha2: "VN", codigoAlpha3: "VNM" },
    { id: 764, nombrePais: "TAILANDIA", continentePais: "ASIA", poblacionPais: 70000000, capital: "BANGKOK", bandera: "https://flagcdn.com/w320/th.png", codigoAlpha2: "TH", codigoAlpha3: "THA" },
    { id: 496, nombrePais: "MONGOLIA", continentePais: "ASIA", poblacionPais: 3300000, capital: "ULAN BATOR", bandera: "https://flagcdn.com/w320/mn.png", codigoAlpha2: "MN", codigoAlpha3: "MNG" },
    { id: 364, nombrePais: "IRAN", continentePais: "ASIA", poblacionPais: 85000000, capital: "TEHERAN", bandera: "https://flagcdn.com/w320/ir.png", codigoAlpha2: "IR", codigoAlpha3: "IRN" },
    { id: 682, nombrePais: "ARABIA SAUDITA", continentePais: "ASIA", poblacionPais: 35000000, capital: "RIAD", bandera: "https://flagcdn.com/w320/sa.png", codigoAlpha2: "SA", codigoAlpha3: "SAU" },
    { id: 376, nombrePais: "ISRAEL", continentePais: "ASIA", poblacionPais: 9300000, capital: "JERUSALEN", bandera: "https://flagcdn.com/w320/il.png", codigoAlpha2: "IL", codigoAlpha3: "ISR" },
  
    { id: 566, nombrePais: "NIGERIA", continentePais: "AFRICA", poblacionPais: 206000000, capital: "ABUYA", bandera: "https://flagcdn.com/w320/ng.png", codigoAlpha2: "NG", codigoAlpha3: "NGA" },
    { id: 818, nombrePais: "EGIPTO", continentePais: "AFRICA", poblacionPais: 104000000, capital: "EL CAIRO", bandera: "https://flagcdn.com/w320/eg.png", codigoAlpha2: "EG", codigoAlpha3: "EGY" },
    { id: 710, nombrePais: "SUD AFRICA", continentePais: "AFRICA", poblacionPais: 60000000, capital: "CIUDAD DEL CABO", bandera: "https://flagcdn.com/w320/za.png", codigoAlpha2: "ZA", codigoAlpha3: "ZAF" },
    { id: 404, nombrePais: "KENIA", continentePais: "AFRICA", poblacionPais: 54000000, capital: "NAIROBI", bandera: "https://flagcdn.com/w320/ke.png", codigoAlpha2: "KE", codigoAlpha3: "KEN" },
    { id: 231, nombrePais: "ETIOPIA", continentePais: "AFRICA", poblacionPais: 115000000, capital: "ADIS ABEBA", bandera: "https://flagcdn.com/w320/et.png", codigoAlpha2: "ET", codigoAlpha3: "ETH" },
    { id: 288, nombrePais: "GHANA", continentePais: "AFRICA", poblacionPais: 31000000, capital: "ACRA", bandera: "https://flagcdn.com/w320/gh.png", codigoAlpha2: "GH", codigoAlpha3: "GHA" },
    { id: 504, nombrePais: "MARRUECOS", continentePais: "AFRICA", poblacionPais: 37000000, capital: "RABAT", bandera: "https://flagcdn.com/w320/ma.png", codigoAlpha2: "MA", codigoAlpha3: "MAR" },
    { id: 24, nombrePais: "ANGOLA", continentePais: "AFRICA", poblacionPais: 33000000, capital: "LUANDA", bandera: "https://flagcdn.com/w320/ao.png", codigoAlpha2: "AO", codigoAlpha3: "AGO" },
    { id: 788, nombrePais: "TUNEZ", continentePais: "AFRICA", poblacionPais: 12000000, capital: "TUNEZ", bandera: "https://flagcdn.com/w320/tn.png", codigoAlpha2: "TN", codigoAlpha3: "TUN" },
    { id: 12, nombrePais: "ALGERIA", continentePais: "AFRICA", poblacionPais: 43000000, capital: "ARGEL", bandera: "https://flagcdn.com/w320/dz.png", codigoAlpha2: "DZ", codigoAlpha3: "DZA" },
  
    { id: 36, nombrePais: "AUSTRALIA", continentePais: "OCEANIA", poblacionPais: 25690000, capital: "CANBERRA", bandera: "https://flagcdn.com/w320/au.png", codigoAlpha2: "AU", codigoAlpha3: "AUS" },
    { id: 554, nombrePais: "NUEVA ZELANDA", continentePais: "OCEANIA", poblacionPais: 5000000, capital: "WELLINGTON", bandera: "https://flagcdn.com/w320/nz.png", codigoAlpha2: "NZ", codigoAlpha3: "NZL" },
    { id: 242, nombrePais: "FIJI", continentePais: "OCEANIA", poblacionPais: 900000, capital: "SUVA", bandera: "https://flagcdn.com/w320/fj.png", codigoAlpha2: "FJ", codigoAlpha3: "FJI" },
    { id: 598, nombrePais: "PAPUA NUEVA GUINEA", continentePais: "OCEANIA", poblacionPais: 9000000, capital: "PORT MORESBY", bandera: "https://flagcdn.com/w320/pg.png", codigoAlpha2: "PG", codigoAlpha3: "PNG" },
    { id: 882, nombrePais: "SAMOA", continentePais: "OCEANIA", poblacionPais: 200000, capital: "APIA", bandera: "https://flagcdn.com/w320/ws.png", codigoAlpha2: "WS", codigoAlpha3: "WSM" },
    { id: 776, nombrePais: "TONGA", continentePais: "OCEANIA", poblacionPais: 100000, capital: "NUKU'ALOFA", bandera: "https://flagcdn.com/w320/to.png", codigoAlpha2: "TO", codigoAlpha3: "TON" },
    { id: 548, nombrePais: "VANUATU", continentePais: "OCEANIA", poblacionPais: 300000, capital: "PORT VILA", bandera: "https://flagcdn.com/w320/vu.png", codigoAlpha2: "VU", codigoAlpha3: "VUT" },
    { id: 296, nombrePais: "KIRIBATI", continentePais: "OCEANIA", poblacionPais: 120000, capital: "TARAWA", bandera: "https://flagcdn.com/w320/ki.png", codigoAlpha2: "KI", codigoAlpha3: "KIR" },
    { id: 585, nombrePais: "PALAU", continentePais: "OCEANIA", poblacionPais: 18000, capital: "NGERULMUD", bandera: "https://flagcdn.com/w320/pw.png", codigoAlpha2: "PW", codigoAlpha3: "PLW" },
    { id: 90, nombrePais: "ISLAS SALOMON", continentePais: "OCEANIA", poblacionPais: 700000, capital: "HONIARA", bandera: "https://flagcdn.com/w320/sb.png", codigoAlpha2: "SB", codigoAlpha3: "SLB" }
  ];
  